void triTable();
void generationTable();
void triParInsertion();
void triParSelection();
void triParEchange();
void ShellSort();
void heapsort();
void placer();
void quickSort();
void initialisationQS ();
void triQS();
int verif ();
void slowerFaster ();
