float triTable();
float mainTabTrie();
float mainTabATrie();
void affMenuTri();
void mainTotal();
void generationTable();
void triParInsertion();
void triParSelection();
void triParEchange();
void ShellSort();
void heapsort();
void placer();
void quickSort();
void initialisationQS ();
void triQS();
int verif ();
void slowerFaster ();
int *copieTab();
int *generationTableTriee();
void affichageTabClok();